### ISSUE TITLE
如何解决编译依赖

### ISSUE THREAD

**Issue by shindar90** [phorcys/Taiwu_mods#1]
请问这个项目要依赖什么dll，例如ActorMenu这种类，我找不到相关的引用，已经把太吾里面的dll都试过了

**Comment by phorcys** [comment]
需要 unity tools for visuallstuio
选 Unity .net 3.5 subset 做target
ActorMenu之类的在 Assembly-CSharp.dll里，有简单加密，解开即可

**Comment by narcotics726** [comment]
不知道是否介意分享一下如何解密...简单搜索了一下，不是很明白怎么做

**Comment by shindar90** [comment]
理解了，谢谢。之前没做过游戏，不熟悉这些套路。

**Comment by narcotics726** [comment]
@shindar90 如果成功了的话，能不能麻烦分享一下解密的方法？

**Comment by shindar90** [comment]
> @shindar90 如果成功了的话，能不能麻烦分享一下解密的方法？

还没试，加载这个dll的过程自然有解密的方法，反向看一下应该就能知道

**Comment by narcotics726** [comment]
@shindar90 我反向以后...看不懂...野生程序员看到 C 就脑袋大

成功后如果方便的话请分享一下，非常感谢

**Comment by ZweiLee** [comment]
@phorcys 哥们，能把你适配过的UnityModManagerNet.dll 上传上来了吗，谢谢。
我这个问题应该是那个dll的原因吧？
![image](https://user-images.githubusercontent.com/16412376/46110458-40617d00-c216-11e8-9e41-c6daf17ffcd1.png)
