### ISSUE TITLE
请问现在基础资源可以替换图片资源了吗?

### ISSUE THREAD

**Issue by TeddyForest** [phorcys/Taiwu_mods#123]
请问基础资源框架能否做图片资源导入呢? 不好意思我这裡是英化组,透过基础资源框架修改文本,但有些"图文"没法做翻译,想寻求您这辺的协助,感谢!

**Comment by phorcys** [comment]
你可以列一下那些资源需要导入

目前BaseResourceMod 只支持了后续动态载入的资源图片
没有支持打包在基础asset包里的
这些需要手动添加路径和文件名
如果你有需要修改部分，可以给我一份列表
如果需要修改大部分，且你确定需要，我下周可以生成一个列表，把里面需要替换的都替换掉
但是随着游戏不断更新。这个列表可能也需要维护
（其实本身很简单，如果你熟悉了的话，可以自己fix之后发pull request 过来）

**Comment by TeddyForest** [comment]
我在英化时遇到个BUG, 新版本导出的 Fame_Date.txt 似乎无法写入? 请问您是否可以协助测试?

**Comment by TeddyForest** [comment]
error to cate fame_date  还有 villagename_date  我的UMM是 0.12.2  BRM是1.0.7版

**Comment by TeddyForest** [comment]
![image](https://user-images.githubusercontent.com/44433979/50038082-ca222900-0054-11e9-87c2-e67df2299606.png)
![image](https://user-images.githubusercontent.com/44433979/50038088-d908db80-0054-11e9-8a4f-91c335fa574e.png)

**Comment by phorcys** [comment]
@TeddyForest 
7a141d55b0312f9999ff07903be590a2a7ef14ab
提交更新了BaseResourceMod 1.0.8 ，可能修复了 fame date 和villiage name的问题
你可以测试一下

至于图片，你可以列一下

**Comment by TeddyForest** [comment]
> 提交更新了BaseResourceMod 1.0.8 ，可能修复了 fame date 和villiage name的问题
> 你可以测试一下
> 
> 至于图片，你可以列一下

好的,非常感谢你,等你的回復等好久,图片需要我把档名列出来吗?先前的回復中有列出资料夹

**Comment by sth4nothing** [comment]
@TeddyForest 你来加Q群吧：903110962
