### ISSUE TITLE
NPCScan mod  在系统分辨率16:9游戏分辨率4:3下显示不正确

### ISSUE THREAD

**Issue by Hoyifei** [phorcys/Taiwu_mods#135]
建议使用Screen.currentResolution.width
另外编译时报错 未能解析主引用“Assembly-CSharp”，因为它对 .NET Framework 程序集“mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089”具有间接依赖关系，而该程序集的版本为“4.0.0.0”，高于当前目标框架中的版本“2.0.0.0”	怎么办

**Comment by sth4nothing** [comment]
**编译的问题**
> 请按照首页的readme使用genvsproj.cmd创建解决方案来编译mod。

**Comment by Hoyifei** [comment]
系统的分辨率是1920*1080
游戏的大概是1280*960
调出来的方法是系统调到4：3，全屏游戏，切系统调16：9，切回游戏选窗口(由于不明原因我根本没有调分辨率的选项，大概因为在用虚拟机，而且最近更新后再也无法改回16：9的分辨率)

**Comment by sth4nothing** [comment]
@Hoyifei 这个就不好测试了。
要弄个你这个测试环境太折腾了。得先装个vbox，然后装win虚拟机。再安装steam、太吾……

**Comment by sth4nothing** [comment]
改注册表？
