### ISSUE TITLE
关于基本框架的图片置入及键盘快捷键的问题

### ISSUE THREAD

**Issue by b95103022** [phorcys/Taiwu_mods#138]
1/11更新后，原本使用基本框架替换的Texture全部失效，不知道是否是更新系统后改了路径。
另外键盘快捷键MOD则是无法显示功能，有大佬能帮忙看一看吗？谢谢。

**Comment by fenghou1st** [comment]
基础资源框架又更新了一版，上次 bug 没修复完全。

**Comment by b95103022** [comment]
收到，感谢大老的维护，请受小弟一拜
