### ISSUE TITLE
0.18新版本的快捷键mod出问题了

### ISSUE THREAD

**Issue by fanzhen1** [phorcys/Taiwu_mods#146]
似乎没有失效，但是在管理界面不显示名称

**Comment by fenghou1st** [comment]
我这里能够正常显示。

**Comment by fanzhen1** [comment]
奇怪了，也没发现错误啊。我更新游戏后，重装UnityModManager，进入游戏，快捷键键位全部归零，这是我凭着记忆重设的。

![image](https://user-images.githubusercontent.com/20765667/52177015-1e948a00-27f6-11e9-845b-03e7ac2d136f.png)
![image](https://user-images.githubusercontent.com/20765667/52177020-3835d180-27f6-11e9-8fe0-f0b12d8373d0.png)

**Comment by fenghou1st** [comment]
这是前几个版本的 bug，你确定下载的是最新的吗？

**Comment by fenghou1st** [comment]
建议完全删除旧版本，再下载一遍最新的试试。
