### ISSUE TITLE
NPCscan1.7.2版本报错

### ISSUE THREAD

**Issue by yyh120120** [phorcys/Taiwu_mods#152]
搜索前任太吾和部分npc时出现红字，搜索不到。
![k n c2873dg7 bko2wx1z](https://user-images.githubusercontent.com/47496633/52533101-cd424880-2d69-11e9-9451-ed2cd0721181.png)

**Comment by yyh120120** [comment]
求大佬修复呀

**Comment by yunling121** [comment]
> 求大佬修复呀

nga已更新1.7.3

**Comment by yyh120120** [comment]
拜谢大佬，好人一生平安！
