### ISSUE TITLE
GUI仓库不能把物品放到仓库中去

### ISSUE THREAD

**Issue by scolGit** [phorcys/Taiwu_mods#156]
正式版本0.18.0, 报错 MissingMethodException: void DateFile.ChangeTwoActorItem(int,int,int,int,int)

![image](https://user-images.githubusercontent.com/24309603/52656326-10024d00-2f31-11e9-83c0-57159ca321b0.png)
![image](https://user-images.githubusercontent.com/24309603/52656366-2d371b80-2f31-11e9-9d72-e8d763c8a355.png)

**Comment by sth4nothing** [comment]
已经修复，但是还没有release而已
