### ISSUE TITLE
Guiwarehouse 1.2.6 报错  版本v0.1.8.8 测试分支

### ISSUE THREAD

**Issue by 742799201** [phorcys/Taiwu_mods#159]
当存入14奇书的时候会有红字。如果忽视红字，就会有人物在 （京城-00）的bug，应该和奇书争夺有关，目前为止，前往京城-00的人不会回来，而如果去了京城就会在过月的时候红字，然后卡住。
下面上图

![2019-2-18 22-47-14](https://user-images.githubusercontent.com/43740839/52958517-31e74e00-33cf-11e9-82c3-16ff10dfc5c3.png)

![1](https://user-images.githubusercontent.com/43740839/52958428-05333680-33cf-11e9-8caa-57c9caa385c4.jpg)

![2](https://user-images.githubusercontent.com/43740839/52958463-14b27f80-33cf-11e9-9230-e6d2df65cade.jpg)

**Comment by sth4nothing** [comment]
@gdjyhjs

**Comment by yunling121** [comment]
遇到同样的问题，但不确定是哪个mod所致，现在mod已全部禁用仍然无法京城过月
