### ISSUE TITLE
下载了dlls里面没有那个gxxx.cmd文件啊？mods文件夹里面有dlls文件夹。

### ISSUE THREAD

**Issue by YellowZhiyi** [phorcys/Taiwu_mods#191]
我是将下载的dlls-190421.zip文件直接拖给UMM0.12安装，显示解压成功。直接这样用，还是还要干什么

**Comment by ciwei100000** [comment]
https://nga.178.com/read.php?tid=16255707

**Comment by HuZhYi** [comment]
> https://nga.178.com/read.php?tid=16255707

看过了，都试过了，安装工具下载默认位置是桌面。。。下了个安装包下来直接解压到mods文件夹内，看了里面的文件全都是unitydll的源码。modsUpdataUI缺乏文档，最新文件指向的还是dlls-190421.zip。现在是把所有mod集成了？还是还要单个下载

**Comment by ciwei100000** [comment]
最新的release里面没有mod，dlls-190421.zip是编译环境。github的源码自己编译一下，把info.json和编译好的dll放到一个文件夹里压缩成zip文件，然后用UMM载入就行了。如果要下载编译好的，老一点的mod可以去上一个release里面找找，新的mod就要去作者发的帖子里面去找了，一般发布在百度贴吧和nga论坛
