### ISSUE TITLE
基础资源无法替换服装立绘

### ISSUE THREAD

**Issue by ganixil** [phorcys/Taiwu_mods#192]
游戏版本是0.2.2.2
UMM版本是0.12.2
BRM版面是1.0.12

BRM可以读取到Data和Texture文件夹，可是Data文件夹中的txt在found之后会有一个inject的步骤，可是Texture里的png找到了却不会inject. 不知道为什么加载了好多次，看了好多遍log，立绘的png都加载不进去。

**Comment by 13816945610** [comment]
我遇到同样的问题
翻了下代码
应该是AddNewSpriteFromTexturePNG这个函数里报的。
var newsprite = Sprite.Create(toload, new Rect(0, 0, toload.width, toload.height), new Vector2(0, 0), 100)
这个精灵创建为null？
