### ISSUE TITLE
UnityModManager 最新版哪里下载？

### ISSUE THREAD

**Issue by wuminmin** [phorcys/Taiwu_mods#194]
UnityModManager 最新版哪里下载？

**Comment by ciwei100000** [comment]
[[太吾学社]MOD使用经验分享/写给小白的MOD查错教程+个人向MOD介绍](https://bbs.nga.cn/read.php?tid=16255707&_fp=2)这里有详细攻略，看完就知道了。

**Comment by 1362563840** [comment]
问一下 如果我没理解错 
basedresourcemod 是基础mod 如果要改进mod就用这个为基础
但是umm 是可以用来加载各种mod, 关键是umm在这个github哪里 因为至少要有一个.exe 加上一些额外文件, 但是在这个github上没找到umm的文件夹

**Comment by ciwei100000** [comment]
> 问一下 如果我没理解错
> basedresourcemod 是基础mod 如果要改进mod就用这个为基础
> 但是umm 是可以用来加载各种mod, 关键是umm在这个github哪里 因为至少要有一个.exe 加上一些额外文件, 但是在这个github上没找到umm的文件夹 虽然umm不怎么需要更新 可万一呢
> 
> 在另外一个github上看到umm相关文件 但没找到.exe 是不是还要编译成.exe 文件

[https://bbs.nga.cn/read.php?tid=15166431](https://bbs.nga.cn/read.php?tid=15166431)这里有编译好的，去附件里找
