### ISSUE TITLE
依赖问题

### ISSUE THREAD

**Issue by ZweiLee** [phorcys/Taiwu_mods#2]
@phorcys 哥们， 能把你适配过的UnityModManagerNet.dll上传吗，谢谢。
我这个问题应该是那个dll导致的把？
![image](https://user-images.githubusercontent.com/16412376/46110576-a51cd780-c216-11e8-9ca7-1abd8b4cc88a.png)

**Comment by phorcys** [comment]
这个和 unitymodmanager没关系
你把unitymodmanager 运行安装后，修改过的 Assembly-CSharp.dll 解开作为依赖即可

**Comment by ZweiLee** [comment]
@phorcys 感觉找到的Main的类型异常。但并不是namespace的原因把。
感觉是Load方法的时候里少了某个加载文件。
unitymodmanager是这个仓库里的吗？https://github.com/newman55/unity-mod-manager
如果namespace不对会提示到未加载的。
![image](https://user-images.githubusercontent.com/16412376/46134197-e8a62e80-c274-11e8-8f8b-0808dfa9272d.png)

**Comment by phorcys** [comment]
> @phorcys 感觉找到的Main的类型异常。但并不是namespace的原因把。
> 感觉是Load方法的时候里少了某个加载文件。
> unitymodmanager是这个仓库里的吗？https://github.com/newman55/unity-mod-manager
> 如果namespace不对会提示到未加载的。
> ![image](https://user-images.githubusercontent.com/16412376/46134197-e8a62e80-c274-11e8-8f8b-0808dfa9272d.png)

你这提示是找不到FakerGongFa.Main 这个类啊
具体详细信息，有 游戏的log
C:\Users\<用户名>\AppData\LocalLow\Conch Ship Game\The Scroll Of Taiwu Alpha V1.0\output_log.txt
里面有具体异常信息，

**Comment by phorcys** [comment]
> 想问一下能不能提供Assembly-CSharp.dll的解密和重新加密的工具？

并不能

**Comment by ZweiLee** [comment]
> > @phorcys 感觉找到的Main的类型异常。但并不是namespace的原因把。
> > 感觉是Load方法的时候里少了某个加载文件。
> > unitymodmanager是这个仓库里的吗？https://github.com/newman55/unity-mod-manager
> > 如果namespace不对会提示到未加载的。
> > ![image](https://user-images.githubusercontent.com/16412376/46134197-e8a62e80-c274-11e8-8f8b-0808dfa9272d.png)
> 
> 你这提示是找不到FakerGongFa.Main 这个类啊
> 具体详细信息，有 游戏的log
> C:\Users<用户名>\AppData\LocalLow\Conch Ship Game\The Scroll Of Taiwu Alpha V1.0\output_log.txt
> 里面有具体异常信息，

```这张图是把namespace改错以后出的提示。
-------------------------------------------------------------------
但namespace正常的时候会出现第一图的异常:TypeLoadException类：类型加载失败发生时引发的异常。我有点自闭了。。。。

**Comment by ZweiLee** [comment]
@phorcys 

我就是直接用你代码编译也是同样的错误。
问题还是在那个unitymodmanager依赖把？哥们，你修改过unitymodmanager的源码把。
能把你的unitymodmanager打个dll出来么。。
不然我看原版的unitymodmanager是在太吾install不了的，读不到那个加密Assembly-CSharp.dll的。

**Comment by phorcys** [comment]
unitymodmanager没有dll
你们说的那些代码已经注入到assembly-csharp.dll里了

你们需要的是解密经过安装的assembly-csharp.dll
里面都有

**Comment by neoedmund** [comment]
这个有点绕。不过上面都说清楚了。 就是解密工具可以见：https://github.com/vizv/TaiwuDecompiler 
（对用unitymodmanager注入过的assembly-csharp.dll使用后，会生成assembly-csharp_<HASH>.dll, 这个就是编译用的assembly-csharp.dll）
