### ISSUE TITLE
人物浮动信息无法显示人物关系界面的人物信息

### ISSUE THREAD

**Issue by falorway** [phorcys/Taiwu_mods#202]
在最新版本的太吾，浮动信息1.4.4出现以下错误；
无法显示人物关系界面的浮动信息（这点比较难受），浮动窗口会移动到游戏窗口上缘，啥都看不见。

即使已经勾选显示已故人物信息，在人物的轮回界面，鼠标移动到前世身上依然不会出现前世的浮动信息窗口

**Comment by ciwei100000** [comment]
1.4.6版本已经修复
