### ISSUE TITLE
人物浮动信息显示主角武功属性错误

### ISSUE THREAD

**Issue by grf123** [phorcys/Taiwu_mods#204]
如题，人物浮动信息MOD，当显示主角信息时，其他数值都正确的。只有武功一系。内功，指法，一直到软兵，这部分现值全部显示的是0.资质显示的是对的。
只有显示主角有这个问题。

**Comment by ciwei100000** [comment]
你用的人物浮动信息MOD是什么版本？1.4.4显示主角信息只显示促织福源和生平遗惠，不会显示其他信息。

**Comment by ciwei100000** [comment]
1.4.6版本已经修复
