### ISSUE TITLE
想制作MOD，请教大佬几个问题

### ISSUE THREAD

**Issue by BeyondW** [phorcys/Taiwu_mods#212]
大佬好，我看了一些资料对于制作MOD入门还有一些疑惑的地方，请教一下大佬。

我理解的是通过反编译Assemble-CSharp.dll, 修改其中的逻辑然后生成新的dll覆盖原dll来达到修改的目的。但是我发现两个问题
1.新版的Assemble-CSharp.dll无法直接反编译，是因为加密的原因么？之前的是如何进行反编译的呢
2.UMM的MOD制作似乎跟我的理解不太一样，并没有直接替换Assemble-CSharp.dll，请教下UMM的MOD的原理是怎样的？

萌新有长期的编程经验，但是对于反编译和MOD制作还是初次尝试。希望能得到您的引路。

**Comment by fenghou1st** [comment]
群里看到你了, 群里交流吧, 那儿人多, 交流方便些.

**Comment by YichengDing** [comment]
大佬可以也拉我一下吗,最近在用dnspy看源码,有点看不懂....希望大佬指点迷津
