### ISSUE TITLE
BaseResourceMod1.0.14.4没有打包吗？

### ISSUE THREAD

**Issue by bigdemage** [phorcys/Taiwu_mods#222]
我在git的提交下看到两个大佬在5天前提交了代码，并且在更新日志中说1.0.14.4兼容0.2.5X，但是再release中已经没看到zip包，最新的只有1.0.12的，打包上传下吧大佬

**Comment by lluoshangl** [comment]
> 我在GIT中的提交下看到两个大佬在5天前提交了代码，并且在更新日志中说1.0.14.4兼容0.2.5X，但是再释放中已经没看到拉链包，最新的只有1.0。 12的，打包上传下吧大佬

https://bbs.nga.cn/read.php?tid=17833638
