### ISSUE TITLE
能否添加mod编译的步骤到readme？

### ISSUE THREAD

**Issue by brithbutter** [phorcys/Taiwu_mods#226]
项目主您好，
很感谢您分享这些游戏mod不过这里都只有mod源码。可以请您添加将源码文件编译为可以直接放入Mods文件夹的操作步骤么？
谢谢

**Comment by FDKPIBC** [comment]
只需要下载一个Visual Studio 2019(以下简称vs)(保证安装4.7或以上版本的),将本项目拉取到你的本地使用genvsproj.cmd执行创建解决方案,创建好后在当前目录下build文件夹Taiwu_Mods.sln,点击vs界面的编译按钮即可完成.(亦或者看[微软官方文档](https://docs.microsoft.com/zh-cn/previous-versions/visualstudio/visual-studio-2013/cyz1h6zd(v=vs.120)?redirectedfrom=MSDN))

**Comment by brithbutter** [comment]
谢谢指点

**Comment by CyanCloverFern** [comment]
> 只需要下载一个Visual Studio 2019(以下简称vs)(保证安装4.7或以上版本的),将本项目拉取到你的本地使用genvsproj.cmd执行创建解决方案,创建好后在当前目录下build文件夹Taiwu_Mods.sln,点击vs界面的编译按钮即可完成.(亦或者看[微软官方文档](https://docs.microsoft.com/zh-cn/previous-versions/visualstudio/visual-studio-2013/cyz1h6zd(v=vs.120)?redirectedfrom=MSDN))

您好，那些所需要的库文件有没有什么整合好的包之类的？或者你们mod制作者们有没有群之类的？

**Comment by Yan-Zero** [comment]
> > 只需要下载一个Visual Studio 2019（以下简称vs）（保证安装4.7或以上版本的），将本项目拉取到你的本地使用genvsproj.cmd执行创建解决方案，创建好后在当前目录下生成文件夹Taiwu_Mods.sln，单击vs界面的编译按钮即可完成。（亦或者看[微软官方文档](https://docs.microsoft.com/zh-cn/previous-versions/visualstudio/visual-studio-2013/cyz1h6zd(v=vs.120)?redirectedfrom=MSDN)）
> 
> 您好，~那些所需要的库文件有没有什么整合好的包之类的~或者你们mod制作者们有没有群之类的？
> 
> 找到build依赖了，还是问一下有没有群之类的

QQ群 903110962
