### ISSUE TITLE
BaseResourceMod支持导出事件图片吗？

### ISSUE THREAD

**Issue by slovenlulu** [phorcys/Taiwu_mods#246]
就是指主角和NPC交流，或者过月时npc来找主角的事件里的那些背景图片。
event_date.txt第三列的数字就对应这一图片的编号。为0的时候就是主角所处的地形对应的图片。
也可以手动设定特殊图片比如创建人物事件的图片的编号就是1039，将其他事件的第三列改为1039，在弹出事件时就会变成那张特殊图片。
我想新增一些这样的图片，应该用什么姿势呢？

**Comment by ciwei100000** [comment]
以前可以，现在游戏改了加载机制，暂时不行了。
