### ISSUE TITLE
cmake生成解决方案之后build保错

### ISSUE THREAD

**Issue by Femars** [phorcys/Taiwu_mods#256]
我用vs2019打开Taiwu_Mods.sln之后，直接编译整个工程 然后就提示找不到包，请问怎么回事啊
![QQ截图20200127204305](https://user-images.githubusercontent.com/23731822/73175793-f0feca00-4145-11ea-8916-581fdbb531f9.png)

**Comment by fenghou1st** [comment]
dll 包没下载成功吧? 仔细看看运行 genvsproj.cmd 之后的命令行输出.

**Comment by Femars** [comment]
> dll 包没下载成功吧? 仔细看看运行 genvsproj.cmd 之后的命令行输出.
重新下载了一下 还是这样子 应该是部分包依赖没有 这7个都编译成功了
![QQ截图20200128114118](https://user-images.githubusercontent.com/23731822/73234002-3e6d4c80-41c3-11ea-901f-c23858822e91.png)

**Comment by fenghou1st** [comment]
你上面报的缺少的 dll, 在 dll 包里都有, 而且也是你截图的这几个 mod 必需的. 如果这几个编译成功而其他不成功, 可能是其他 mod 配置有问题. 建议删掉 build 文件夹下的所有东西, 重新运行一遍 genvsproj.cmd.

**Comment by fenghou1st** [comment]
另外, 建议到QQ群交流, 群号见 https://github.com/phorcys/Taiwu_Mods_Tools 说明.

**Comment by Femars** [comment]
> 另外, 建议到QQ群交流, 群号见 https://github.com/phorcys/Taiwu_Mods_Tools 说明.

原来的工程我已经在pull了一次，重新build之后还是会报错 而且好像是固定的那几个mod出问题 其他的可以
