### ISSUE TITLE
StorageCheck 1.0.5 Bug报告

### ISSUE THREAD

**Issue by Eriyck** [phorcys/Taiwu_mods#27]
似乎计数的时候，当前显示的物品的耐久会重复计数到总耐久里面。比如：
1.一本2/2的书会显示总耐久4/4
2.两个菜品，2/2和3/3，在看2/2的总耐久的时候显示7/7. 看3/3的时候显示8/8

**Comment by phorcys** [comment]
收到，下次更新修复
