### ISSUE TITLE
genvsproj.cmd中没有steamdir呀

### ISSUE THREAD

**Issue by w867066886** [phorcys/Taiwu_mods#270]
我看只有genvsproj.sh里有这个变量？

**Comment by RedContritio** [comment]
steam 正常安装的话应该直接在系统里有，你直接执行试试。

**Comment by w867066886** [comment]
我直接运行会报找不到steam目录的错，我是默认安装的
  Searching for taiwu install dir...
Did not find taiwu install folder in any steam library

**Comment by fenghou1st** [comment]
找不到就直接手动添加太吾的目录到 genvsproj.sh 里吧, 把那块搜索太吾目录的代码删了.

**Comment by ooo125258** [comment]
在这儿手动加就行，应该是在第31行左右。
                ECHO 下面这行就是新加的_记得删掉本句_以及把下面那行改成你自己的steam位置
                SET libraryPath="C:\\Program Files (x86)\\Steam"
                SET libraryPath=!libraryPath:~1%!
                SET libraryPath=!libraryPath:\\=\!
                ECHO Searching steam library path !libraryPath!...

                SET TAIWUDIR="!libraryPath!\steamapps\common\The Scroll Of Taiwu"

**Comment by Knight-JNXU** [comment]
这 readme 我真是醉了
