### ISSUE TITLE
半懂不懂的编译方法

### ISSUE THREAD

**Issue by ooo125258** [phorcys/Taiwu_mods#276]
各位，我始终是没找着无论是在nga还是在贴吧哪儿告诉你怎么编译的。这让我一个没写过C#没怎么用过VS的人很苦手啊。
踉踉跄跄编译了一下，俺寻思效果还可以？（绿皮转化中）

1）下载VS2019或2017，确保你同时选中安装了C#支持和.NET支持

2）github下载源代码

3）原文：“修改genvsproj.cmd，将里面的STEAMDIR设置为本机太吾绘卷安装目录”
genvsproj.cmd会去你的注册表里面搜索steam预设的安装位置，但是我太吾绘卷没安装在那儿，或者别的其它原因找不到。
在这种情况下请到第36行“SET TAIWUDIR="!libraryPath!\steamapps\common\The Scroll Of Taiwu” 改为 
SET libraryPath="C:\Program Files (x86)\Steam\steamapps\common\The Scroll Of Taiwu".
第31行
这是我的安装位置，你们应该改成你们自己的安装位置。

4）原文：“如果没有cmake，安装 cmake最新版本”
请回头检视一下你的第一步，找到visual studio installer ->installed->Visual Studio 2019->Modify->Individual components->搜索cmake， 确定"C++ CMake tools for Windows"已经安装。如果没有，请安装它。

5）原文：“命令行运行 genvsproj.cmd, 会自动下载依赖的dlls，并生成Visual Studio的解决方案Taiwu_Mods.sln到build目录下”
为保证正确运行，请在你的源代码位置添加以下空文件夹：
\build
\build\Scroll
\build\Of
\build\Taiwu
否则会报错，找不到以上文件夹。但实际上后面三个一点用没有。
运行之后工程会加载到build文件夹下

6）编译。到这儿了我觉得熟悉IDE的人应该已经缓过神来了。
启动VS2019，打开\build\Taiwu_Mods.sln。工程会自动加载。然后Build->build solution，或者Build->Rebuild Solution(假如你想再来一遍)，或者到右面的solution explorer右键你想编译的mod，选择Rebuild。
编译出来的文件会出现在\build\dlls文件夹下。对没有ZIP。我不知道zip是怎么自动包出来的，不过我手动也能包（就是7），所以我也不在乎了。

7）大佬说“如果游戏mod目录下存在mod同名文件夹，则自动复制dll到 游戏mods目录下对应mod目录内”，但实际上有的时候并不会。
好的，在游戏安装目录The Scroll Of Taiwu\Mods\文件夹下建立你要的mod文件夹，例如NpcScan。
源代码位置\NpcScan\Info.json复制到这个文件夹
源代码位置\NpcScan\Settings.xml复制到这个文件夹
源代码位置\build\dlls\NpcScan.dll复制到这个文件夹
你可以去折腾别的mod了

8）完事，打开游戏。

注意啊，里面不是所有mod都能用的。
你build完后自个儿检视以下你要的那个mod是不是真的build 成功了。
========== Rebuild All: 67 succeeded, 14 failed, 0 skipped ==========

**Comment by Heavynest** [comment]
同没写过csharp不熟悉vs，感谢大佬

**Comment by j14nWe1** [comment]
2021-5-30，我在进行第三步修改genvsproj.cmd的步骤，使用了本issue的方法依然无法奏效，之后把“SET /a integer=!key!+0
            IF NOT !integer!==0 (”加下面的“)"整个删除，再把缩进对齐后运行成功
