### ISSUE TITLE
没有dll？？？After build no dlls were added even though mod are present in /mods folder

### ISSUE THREAD

**Issue by yunguan-wang** [phorcys/Taiwu_mods#85]
首先感谢分享！
不会C， 按照你的步骤做下来，发现没有添加dll到mod里。
求救

L:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Taiwu\Taiwu_mods>genvsproj.cmd
L:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Taiwu\Taiwu_mods>set STEAMDIR="L:\\SteamLibrary\\steamapps\\common\\The Scroll Of Taiwu"
L:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Taiwu\Taiwu_mods>mkdir build
L:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Taiwu\Taiwu_mods>cd build
L:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Taiwu\Taiwu_mods\build>cmake -G "Visual Studio 15 2017" -D STEAMDIR="L:\\SteamLibrary\\steamapps\\common\\The Scroll Of Taiwu"  ..
-- Selecting Windows SDK version 10.0.17134.0 to target Windows 10.0.17763.
-- The CSharp compiler identification is Microsoft Visual Studio 2017
-- The CSharp compiler version is 2.9.0.63208
-- Check for working C# compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/Roslyn/csc.exe
-- Check for working C# compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/Roslyn/csc.exe -- works
-- Finding All subdir that contains mods
-- Found Mod: AutoChooseAttackPart
-- Found Mod: AutoWalk
-- Found Mod: BaseResourceMod
-- Found Mod: CharacterFloatInfo
-- Found Mod: CharmMax
-- Found Mod: DoNotDisturb
-- Found Mod: ExchangeStatPoints
-- Found Mod: HappyLife
-- Found Mod: HerbRecipes
-- Found Mod: HomeShopSort
-- Found Mod: IllustratedHandbook
-- Found Mod: InventorySort
-- Found Mod: KeyBoardShortCut
-- Found Mod: LKX_GongFaSizeToOne
-- Found Mod: LKX_ItemsMerge
-- Found Mod: LKX_NewGameActor
-- Found Mod: LongDaoSSR
-- Found Mod: ManpowerWork
-- Found Mod: MoveBuilding
-- Found Mod: NoMoreTrash
-- Found Mod: NpcScan
-- Found Mod: ReadAssistant
-- Found Mod: ResourceShop
-- Found Mod: Samsara1k
-- Found Mod: SamsaraLock
-- Found Mod: SaveBackup
-- Found Mod: SaveLoadBtns
-- Found Mod: SelectBattleReward
-- Found Mod: ShowBiographyOfTheDead
-- Found Mod: ShowMap
-- Found Mod: ShowRichResources
-- Found Mod: StorageCheck
-- Found Mod: TaiwuBaseClass
-- Found Mod: TaiwuHentai
-- Found Mod: ToTraditionalChinese
-- Found Mod: UseStorageBook
-- Found Mod: UseStorageMaterial
-- Found Mod: VillageHeadOfTaiwu
-- Found Mod: AutoChooseAttackPart  自动变招 Author xyzkljl1  Version 1.0.1 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: AutoWalk   Author Mengluu B;ID  Version 1.0.5 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: BaseResourceMod  基础资源框架 Author phorcys  Version 1.0.4 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: CharacterFloatInfo  人物浮动信息 Author Vallind  Version 1.2.3 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: CharmMax  天人合一 Author logicor  Version 1.0.0 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: DoNotDisTurb  勿扰模式 Author Duncan  Version 1.0.0 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: ExchangeStatPoints  属性转换 Author Duncan  Version 1.1.1 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: HappyLife  安居乐业 Author Vallind  Version 1.0.7 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: HerbRecipes  药引烹饪配方精制材料说明 Author phorcys  Version 2.3.0 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
--      Mod requirements : BaseResourceMod
-- Found Mod: HomeShopSort  秩序 Author xyzkljl1  Version 1.1.2 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: IllustratedHandbook  图鉴/获取物品 Author yyuueexxiinngg  Version 1.0.1 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: InventorySort  商店重新排序 Author phorcys  Version 1.0.5 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: KeyBoardShortCut  键盘快捷键 Author phorcys  Version 1.0.8 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: LKX_GongFaSizeToOne  功法大小1格 Author 小枫泡泡  Version 1.0.2 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: LKX_ItemsMerge  多个物品合并为一个 Author 小枫泡泡  Version 1.0.0 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: LKX_NewGameActor  开始新游戏锁定和自定义特质MOD Author 小枫泡泡  Version 1.0.4 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: LongDaoSSR  龙岛忠仆SSR Author xiaoye1024  Version 1.1.0 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: ManpowerWork  任意资源格子使用人力 Author skeu  Version 1.0.0 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: MoveBuilding  太吾村建筑物搬移 Author Eiffel  Version 1.0.0 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: NoMoreTrash  自动丢弃垃圾 Author xyzkljl1  Version 1.0.1 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: NpcScan  NpcScan Author   Version 1.5.2 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: ReadAssistant  读书助手 Author   Version 1.0.8 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: ResourceShop  贪婪 Author xyzkljl1  Version 1.0.0 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: Samsara1k  轮回1k次 Author sth4nothing  Version 1.1.1 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: SamsaraLock  生生世世 Author logicor  Version 1.0.2 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: SaveBackup  存档自动备份 Author logicor  Version 1.0.0 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
--      Add dll type DotNetZip  from L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/SaveBackup/DotNetZip.dll   for mod SaveBackup
--      Add dll type I18N.West  from L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/SaveBackup/I18N.West.dll   for mod SaveBackup
--      Add dll type I18N  from L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/SaveBackup/I18N.dll   for mod SaveBackup
-- Found Mod: SaveLoadBtns  S/L Author Eiffel  Version 1.0.0 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: SelectBattleReward  选择战利品 Author phorcys  Version 1.0.3 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: ShowBiographyOfTheDead  复仇 Author xyzkljl1  Version 1.0.2 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: ShowMap  ShowMap Author xiaoye1024  Version 1.0.0 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: ShowRichResources  ShowRichResources Author xiaoye1024  Version 1.1.0 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: StorageCheck  库存检查-检查背包仓库是否有此物品 Author phorcys  Version 1.0.7 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: TaiwuBaseClass   Author sth4nothing  Version 0.0.0 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: TaiwuHentai  太污绅士 Author FD  Version 0.0.6 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: ToTraditionalChinese  简繁切换 Author yyuueexxiinngg  Version 1.0.0 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: UseStorageBook  修习仓库中的书 Author sth4nothing  Version 1.0.7 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: UseStorageMaterial  仓库材料使用-使用仓库材料进行制造/淬毒/强化 Author phorcys  Version 1.0.3 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Found Mod: VillageHeadOfTaiwu  太吾村支书 Author sth4nothing  Version 1.1.3 L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build
-- Configuring done
-- Generating done
-- Build files have been written to: L:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/Taiwu/Taiwu_mods/build

**Comment by phorcys** [comment]
cmake --build . 或者打开 build/Taiwu_mods.sln 自己编译
