### ISSUE TITLE
安全問題

### ISSUE THREAD

**Issue by HY-Leung** [phorcys/Taiwu_mods#91]
如果DLL作者不壞好意，在討論放MOD，
不知道的人使用了，被偷STEAM帳號。
在技術上是有可能嗎？

**Comment by phorcys** [comment]
不给管理员权限，偷不到密码

**Comment by HY-Leung** [comment]
本身我对C#/C++不太熟悉。我写MOD是抱学习心态。

以前我下载过一些太吾外挂，说XX项修改，
但一看就知被人加了木马，EXE文件大了几MB。

后来找到原版的XX项修改，
当时感觉奇怪它可自动测到太吾有没有开动运行中。
我相信作者同样有能力去侦测STEAM的运行。
对这种XX项修改的外挂是有所保留不敢使用。

现在这UMM，所有源码都在GITHUB找到，相当放心。
但忽然又想到个问题，贴吧或其他网站有很多MOD没有放在GITHUB，
只是打包好ZIP放出来(有些还附了不知有没有改动的UMM一起打包），他们会不会作怪呢？

其实我不太熟识 HarmonyPatch 的能力，利用了UMM，
原始 CS 能不能可以抓到游戏外面STEAM的帐号呢？

**Comment by linkaixiang4883** [comment]
steam账号安全度还是很高的。用一下steam的手机令牌吧，这样你会安心一些。

**Comment by FDKPIBC** [comment]
@HY-Leung 至少从游戏mod这个切入的角度是不可能的,基本的加载顺序为Steam->游戏->umm->mod,除非是独立的应用否则你根本不可能从mod这边搞的

**Comment by HY-Leung** [comment]
我測試過

>  [HarmonyPatch(typeof(Int32), "Parse", new Type[] { typeof(string) })]
>     public static class Int32_Parse
>     {
>         public static void Prefix(string s)
>         {
>             Main.Logger.Log(s);
>         }
>     }

這樣子是有效果的。同樣原理，不受限於只能改動Mod範圍的內容。

**Comment by FDKPIBC** [comment]
@HY-Leung 无意义...

**Comment by sth4nothing** [comment]
这个是不可能解决得了的。哪怕什么都不注入，只是创建一个进程运行shutdown.exe一样可能造成严重后果。

**Comment by linkaixiang4883** [comment]
还是要加强账号管理意识。玩家安全意识谁都救不了的。
